### ISSUE TITLE
I got some error when I test with roslaunch 

### ISSUE THREAD

**Issue by wugeshenhuaking** [Zhaofeng-Tian/ZebraT-Simulator#1]
Test with roslaunch zebrat `zebrat_with_world.launch`.I got some error.

`ERROR: cannot launch node of type [zebrat/servo_commands.py]: Cannot locate node of type [servo_commands.py] in package [zebrat]. Make sure file exists in package path and permission is set to executable (chmod +x)
`
`[urdf_spawner-5] process has died [pid 30562, exit code 1, cmd /opt/ros/melodic/lib/gazebo_ros/spawn_model -urdf -model zebrat -param robot_description -x 1.0 -y 1.5 -z 0.0 __name:=urdf_spawner __log:=/home/wyw/.ros/log/a43dbf2c-2ce4-11ed-9ff9-80fa5b6846fb/urdf_spawner-5.log].
log file: /home/wyw/.ros/log/a43dbf2c-2ce4-11ed-9ff9-80fa5b6846fb/urdf_spawner-5*.log
`

when i test with rosrun `zebrat keyboard_teleop.py`. I got a error.
`
[rosrun] Couldn't find executable named keyboard_teleop.py below /home/wyw/overlay_ws/src/zebrat
[rosrun] Found the following, but they're either not files,
[rosrun] or not executable:
[rosrun]   /home/wyw/overlay_ws/src/zebrat/scripts/keyboard_teleop.py

`

**Comment by Zhaofeng-Tian** [comment]
Hi, have you made all python files executable by `chmod +x *.py` ?

**Comment by wugeshenhuaking** [comment]
> 

As you said,after I added the command the problem was solved

**Comment by Zhaofeng-Tian** [comment]
Sounds great! Does it work well?

**Comment by wugeshenhuaking** [comment]
@Zhaofeng-Tian very well.thanks for your great work!

**Comment by Zhaofeng-Tian** [comment]
> @Zhaofeng-Tian very well.thanks for your great work!

No problem:)
